version: "3.2"
services:

  luovu:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - dev-db
    volumes:
      - .:/luovu

  dev-db:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: luovu
      POSTGRES_PASSWORD: luovu
      POSTGRES_DB: luovu
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
