# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 09:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'receipts', '0001_initial'), (b'receipts', '0002_auto_20170428_1044'), (b'receipts', '0003_auto_20170428_1057'), (b'receipts', '0004_invoicerow'), (b'receipts', '0005_invoicerow_card_holder_id'), (b'receipts', '0006_invoicereceipt'), (b'receipts', '0007_auto_20170502_1700'), (b'receipts', '0008_invoicerow_card_holder_email_guess'), (b'receipts', '0009_invoicerow_invoice_date'), (b'receipts', '0010_auto_20170503_1102'), (b'receipts', '0011_auto_20170503_1147'), (b'receipts', '0012_auto_20170504_2015'), (b'receipts', '0013_ccuser_slack_id'), (b'receipts', '0014_auto_20171211_0901')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuovuPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('vat_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LuovuReceipt',
            fields=[
                ('luovu_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('luovu_user', models.CharField(blank=True, max_length=255, null=True)),
                ('business_id', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('receipt_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploader', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.date(2017, 4, 28))),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='luovuprice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.LuovuReceipt'),
        ),
        migrations.RenameField(
            model_name='luovuprice',
            old_name='vat_number',
            new_name='vat_percent',
        ),
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('row_identifier', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('card_holder', models.CharField(max_length=100)),
                ('record_date', models.DateField()),
                ('foreign_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foreign_currency_name', models.CharField(blank=True, max_length=5, null=True)),
                ('foreign_currency_rate', models.FloatField(blank=True, null=True)),
                ('cc_code', models.CharField(max_length=10)),
                ('cc_description', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('row_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_holder_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.InvoiceRow')),
                ('luovu_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.LuovuReceipt')),
            ],
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='card_holder_email_guess',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='invoice_date',
            field=models.DateField(default=datetime.date(2017, 5, 3)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='luovuprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='luovureceipt',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicerow',
            name='row_identifier',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CcUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlackChat',
            fields=[
                ('chat_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(to=b'receipts.CcUser')),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoicerow',
            options={'ordering': ('delivery_date', 'row_price')},
        ),
        migrations.AlterModelOptions(
            name='luovureceipt',
            options={'ordering': ('date', 'price')},
        ),
        migrations.AddField(
            model_name='ccuser',
            name='slack_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoicerow',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luovuprice',
            name='accout_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
