# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 10:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LuovuPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('vat_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LuovuReceipt',
            fields=[
                ('luovu_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('luovu_user', models.CharField(blank=True, max_length=255, null=True)),
                ('business_id', models.CharField(blank=True, max_length=20, null=True)),
                ('barcode', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=50, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('receipt_type', models.CharField(blank=True, max_length=50, null=True)),
                ('uploader', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='luovuprice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.LuovuReceipt'),
        ),
    ]
