# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luovuprice',
            old_name='vat_number',
            new_name='vat_percent',
        ),
    ]
