# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-28 10:57
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20170428_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='luovureceipt',
            name='date',
            field=models.DateField(default=datetime.date(2017, 4, 28)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luovureceipt',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
