# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_auto_20170428_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRow',
            fields=[
                ('row_identifier', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('card_holder', models.CharField(max_length=100)),
                ('record_date', models.DateField()),
                ('foreign_currency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('foreign_currency_name', models.CharField(blank=True, max_length=5, null=True)),
                ('foreign_currency_rate', models.FloatField(blank=True, null=True)),
                ('cc_code', models.CharField(max_length=10)),
                ('cc_description', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
                ('row_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
