# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_invoicerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerow',
            name='card_holder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
