# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_invoicerow_card_holder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_by_user', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('linked_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField()),
                ('invoice_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.InvoiceRow')),
                ('luovu_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.LuovuReceipt')),
            ],
        ),
    ]
