# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_invoicereceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicereceipt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
