# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_auto_20170502_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerow',
            name='card_holder_email_guess',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
