# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 06:28
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_invoicerow_card_holder_email_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerow',
            name='invoice_date',
            field=models.DateField(default=datetime.date(2017, 5, 3)),
            preserve_default=False,
        ),
    ]
