# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0009_invoicerow_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luovuprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='luovureceipt',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
