# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_auto_20170503_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='CcUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlackChat',
            fields=[
                ('chat_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('members', models.ManyToManyField(to='receipts.CcUser')),
            ],
        ),
        migrations.AlterModelOptions(
            name='invoicerow',
            options={'ordering': ('delivery_date', 'row_price')},
        ),
        migrations.AlterModelOptions(
            name='luovureceipt',
            options={'ordering': ('date', 'price')},
        ),
    ]
