# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0013_ccuser_slack_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerow',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luovuprice',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
