# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0014_auto_20171211_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicerow',
            name='account_number',
        ),
        migrations.AddField(
            model_name='luovureceipt',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
